//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siteyonetimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sahipler
    {
        public short sahip_id { get; set; }
        public string sahip_ad { get; set; }
        public string sahip_soyad { get; set; }
        public string sahip_tel { get; set; }
        public Nullable<bool> sahip_kiradurum { get; set; }
        public Nullable<bool> sahip_aydatdurum { get; set; }
        public Nullable<bool> gorunurluk { get; set; }
    }
}
